### ISSUE TITLE
Can't run test_x11 test of my lib-crate even with xlib feature enabled

### ISSUE THREAD

**Issue by captchaKing** [AltF02/x11-rs#151]
Cargo.toml:
```[package]
name = "x11lib-test"
version = "0.1.0"
edition = "2021"

[dependencies]
x11 = { version = "2.19.1", features = ["xlib"] }
```
lib.rs:
```use std::ptr;
use x11::xlib::XOpenDisplay;

#[cfg(not(feature = "xlib"))]
pub fn foo() {
    panic!("this example requires `--features xlib`");
}

#[cfg(feature = "xlib")]
pub fn foo() {
    let disp = unsafe { XOpenDisplay(ptr::null()) };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_x11() {
        foo();
    }
}
```
Trying to run **test_x11** test results in panic with: **this example requires `--features xlib`**

**Comment by AltF02** [comment]
Could you provide your current command to run this?

**Comment by captchaKing** [comment]
Just `cargo test`. `cargo test --lib` doesn't work either.

**Comment by AltF02** [comment]
Yeah, it requires the feature xlib. So the correct way would be to run `cargo test --features xlib` although I agree thats kinda counter intuitive. 

Possibly we could default features (including xlib) in testing. What do you think?

**Comment by AltF02** [comment]
No need to apologize, we're all busy sometimes :). Due to how the project is structured atm, it requires a user to go into x11 and x11-dl. This is in my opinion flawed and something to look for in #149. You can either go into one of those to run `cargo test --features xlib` but there's a `Makefile` that does it for us. 

You can run them with 
````
make tests
```

**Comment by AltF02** [comment]
No need to apologize, we're all busy sometimes :), I think it has to do with how your `lib.rs` is made, I'm assuming this is copypaste from examples or the tests. 

You can update it to

```
use x11::xlib::XOpenDisplay;

pub fn foo() {
    let disp = unsafe { XOpenDisplay(ptr::null()) };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_x11() {
        foo();
    }
}
```

We remove them as `#[cfg(feature = "xlib")]` checks for the feature in our local project, but our local project doesn't have that feature so it always runs the above which checks for if it isn't present. You don't really need this as its just something that x11 internally can do. I hope it makes sense! If not? Don't be afraid to ask! 😄
