### ISSUE TITLE
How to use the Xfixes extension?

### ISSUE THREAD

**Issue by m0rphism** [AltF02/x11-rs#158]
I'm trying to use `XFixesSelectSelectionInput`, but I always get `undefined reference`. I tried with most of the feature flags and also have `Xfixes` installed, but still no success. Other functions like `XOpenDisplay` work as expected.

Am I missing something or is there a bug in the bindings? I've noticed that compared to the functionality of other X-libraries, there is also no feature flag specific to Xfixes.

**Comment by m0rphism** [comment]
Thanks for the response. I had some time to give it a closer look and it seems the problem is indeed related to the bindings. I was able to fix it in a local clone of this repo.

In `x11/build.rs` there is no entry for `xfixes`, so `pkgconfig` isn't called for `xfixes`.

Since the `x11_link` macro ignores its `$lib_name` argument, the `libXfixes.so`-file also isn't being linked in here.

Adding a feature flag for `xfixes` in `x11/Cargo.toml`, `x11/build.rs` and `x11-dl/build.rs` fixed the issue for me. I think this would be a reasonable fix, since `xfixes` is a separate library library that is distributed with its own `pkgconfig` file.

**Comment by m0rphism** [comment]
I just realized that `x11-dl` isn't an internal dependency of `x11`, but something else.

The change, that I've described in the previous comment and referenced commit, fixes the issue for me with the `x11` crate, but not with the `x11-dl` crate, which I haven't used before and couldn't find any documentation about.

**Comment by AltF02** [comment]
Thanks for investigating, it seems you are correct. I merged in #118 but I overlooked the fact they forgot to add it to x11-dl. Do you want to create a pr for this? Or should I

**Comment by AltF02** [comment]
`x11` is statically linked, `x11-dl` was created later on to serve for dynamic linking. Allows for more portable executables. You shouldn't have to do much aside from add 1mod xfixes1` in `x11-dl`. The rest is handled inside `xfixes.rs` itself

**Comment by conqp** [comment]
Fixed in https://github.com/AltF02/x11-rs/commit/032d968411cc7686949765c10f9fc3afa27bab41
